global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: mythic_prometheus
    static_configs:
      - targets: ["mythic_prometheus:9090"]
  - job_name: mythic_postgres_exporter
    static_configs:
      - targets: ["mythic_postgres_exporter:9187"]